kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cp-test-b-admin
  namespace: cp-test-b
subjects:
  - kind: Group
    name: "github:webops"
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
